routes/web.php
<?php
Route::middleware('auth')->group( function () {
    Route::get('/', 'DashboardController@index');
    Route::get('/sellsDashboard', 'DashController@sell')->name('sellsDashboard');

    Route::resources([
        'category'     =>  'CategoriesController',
        'product'      =>  'ProductsController',
        'city'         =>  'CitiesController',
        'supplier'     =>  'VendorsController',
        'visitor'      =>  'VisitorsController',
        'log'          =>  'LogsController',
        'campaign'     =>  'CampaignsController',
        'user'         =>  'usersController',
        'permission'   =>  'PermissionsController',
        'driver'       =>  'DriversController',
        'notification' =>  'NotificationsController',
        'blog'         =>  'PostsController'
    ]);


    Route::post('driver/clear', 'DriversController@clear')->name('driver.clear');
});
Auth::routes();


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Campaign.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Morilog\Jalali\CalendarUtils;

class Campaign extends Model
{
    protected $guarded=[];

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
    }

    public function start($value){
        $this->attributes['start'] = CalendarUtils::createDateTimeFromFormat('Y/m/d H:i:s',$value);
    }
    public function end($value){
        $this->attributes['end'] = CalendarUtils::createDateTimeFromFormat('Y/m/d H:i:s',$value);
    }
}

app/Http/Controllers/Api/v1/CampaignsController.php
<?php

namespace App\Http\Controllers\Api\v1;

use App\Campaign;
use App\Http\Controllers\Controller;
use Morilog\Jalali\Jalalian;

class CampaignsController extends Controller
{
    public function getLatestCampaign()
    {
        $campaign = Campaign::latest()->firstOrFail();
        $currentTimeStamp = Jalalian::forge(now())->getTimestamp();
        $campaignStartTimeStamp = Jalalian::forge($campaign->start)->getTimestamp();
        $campaignEndTimeStamp = Jalalian::forge($campaign->end)->getTimestamp();
        if ($currentTimeStamp >= $campaignStartTimeStamp && $currentTimeStamp <= $campaignEndTimeStamp) {
            return response()->json(['type' => 'inCampaign']);
        } else {
            if ($currentTimeStamp <= $campaignStartTimeStamp) {
                return response()->json(['date' => $campaign->start, 'type' => 'waiting']);
            } else {
                return response()->json('no campaign', 404);
            }
        }
    }
}

app/Http/Controllers/CampaignsController.php
<?php

namespace App\Http\Controllers;

use App\Campaign;
use App\Http\Controllers\Controller;
use App\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;
use Morilog\Jalali\Jalalian;
use \Morilog\Jalali\CalendarUtils as CalendarUtils;
class CampaignsController extends Controller
{

    public function index()
    {
        $campaigns = Campaign::paginate('15');
        return view('pages.campaigns.list',compact('campaigns'));
    }

    public function create()
    {
        $products = Product::where('status',1)->get();
        return view('pages.campaigns.create',compact('products'));
    }

    public function store()
    {
        $startDateTimeStr = request('startDate').' ' .request('startTime').':00';
        $endDateTimeStr = request('endDate').' ' .request('endTime').':00';
        $campaign = new Campaign();
        $campaign->name = request('name');
        $campaign->start($startDateTimeStr);
        $campaign->end($endDateTimeStr);
        $campaign->products = serialize(request('selectedProducts'));
        $campaign->save();

        return redirect()->route('campaign.index');

    }

    public function show(Campaign $campaign)
    {
        //
    }


    public function edit(Campaign $campaign)
    {
        //
    }


    public function update(Request $request, Campaign $campaign)
    {
        //
    }

    public function destroy(Campaign $campaign)
    {
        $campaign->delete();
        return redirect()->route('campaign.index');
    }
}

resources/views/pages/campaigns/create.blade.php
@extends('master')

@section('breadcrumb')
    <h3 class="page-title">دسته‌بندی جدید</h3>
    <!-- begin::breadcrumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">داشبورد</a></li>
            <li class="breadcrumb-item"><a href="{{route('category.index')}}">لیست دسته‌بندی‌ها</a></li>
            <li class="breadcrumb-item active" aria-current="page">دسته‌بندی جدید</li>
        </ol>
    </nav>
    <!-- end::breadcrumb -->
@endsection
@section('content')
    <div class="row">
        <div class="col-md-9">
            <div class="card">
                <div class="card-body">
                    <form action="{{route('campaign.store')}}" method="post" enctype="multipart/form-data" class="needs-validation" novalidate="">
                        @csrf
                        <div class="form-group">
                            <label for="">نام کمپین</label>
                            <input type="text" name="name" id="" class="form-control" placeholder="" aria-describedby="helpId">
                        </div>
                        <div class="form-group">
                            <select multiple="multiple" size="10" name="selectedProducts[]" class="form-control">
                                @foreach($products as $product)
                                    <option value="{{$product->id}}">{{$product->title}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-4">
                                    <label for="">تاریخ شروع کمپین</label>
                                    <input type="text" name="startDate" class="date form-control text-left" dir="ltr" autocomplete="off">
                                </div>
                                <div class="col col-md-2">
                                    <label for="">زمان </label>
                                    <div class="input-group clockpicker-autoclose-demo">
                                        <div class="input-group-prepend">
									<span class="input-group-text">
										<i class="fal fa-clock"></i>
									</span>
                                        </div>
                                        <input type="text" class="form-control text-left" name="startTime" dir="ltr" autocomplete="off"/>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <label for=""> تاریخ پایان کمپین</label>
                                    <input type="text" name="endDate" class=" date form-control text-left" dir="ltr" autocomplete="off">
                                </div>
                                <div class="col col-md-2">
                                    <label for="">زمان </label>
                                    <div class="input-group clockpicker-autoclose-demo">
                                        <div class="input-group-prepend">
									<span class="input-group-text">
										<i class="fal fa-clock"></i>
									</span>
                                        </div>
                                        <input type="text" class="form-control text-left" name="endTime" dir="ltr" autocomplete="off"/>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-success">ذخیره</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('styles')
    <link rel="stylesheet" href="{{asset('vendors/dual-list/bootstrap-duallistbox.min.css')}}">
    <!-- Clockpicker -->
    <link rel="stylesheet" href="{{asset('vendors/clockpicker/bootstrap-clockpicker.min.css')}}" type="text/css">
    <!-- Datepicker -->
    <link rel="stylesheet" href="{{asset('vendors/datepicker-jalali/bootstrap-datepicker.min.css')}}">
@endsection
@section('scripts')
    <script>
        //  Form Validation
        window.addEventListener('load', function () {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function (form) {
                form.addEventListener('submit', function (event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    </script>
    <script src="{{asset('vendors/dual-list/jquery.bootstrap-duallistbox.js')}}"></script>
    <script>
        var demo1 = $('select[name="selectedProducts[]"]').bootstrapDualListbox();
    </script>
    <script src="{{asset('vendors/datepicker-jalali/bootstrap-datepicker.min.js')}}"></script>
    <script src="{{asset('vendors/datepicker-jalali/bootstrap-datepicker.fa.min.js')}}"></script>
    <script src="{{asset('assets/js/examples/datepicker.js')}}"></script>
    <script src="{{asset('vendors/clockpicker/bootstrap-clockpicker.min.js')}}"></script>
    <script src="{{asset('assets/js/examples/clockpicker.js')}}"></script>
@endsection

resources/views/pages/campaigns/list.blade.php
@extends('master')

@section('breadcrumb')
    <h3 class="page-title">لیست کمپین‌ها</h3>
    <!-- begin::breadcrumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">داشبورد</a></li>
            <li class="breadcrumb-item active" aria-current="page">لیست کمپین‌ها</li>
        </ol>
    </nav>
    <!-- end::breadcrumb -->
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                @if($campaigns->total() > $campaigns->perPage())
                    <div class="card-footer">{{$campaigns->links()}}</div>
                @endif
                <div class="card-body">
                    @if(count($campaigns))
                        <table class="table" id="dataTable">
                            <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">نام</th>
                                <th scope="col">تاریخ شروع</th>
                                <th scope="col">تاریخ پایان</th>
                                <th scope="col">تاریخ ایجاد</th>
                                <th scope="col">تاریخ ویرایش</th>
                                <th class="text-right" scope="col"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($campaigns as $campaign)
                                <tr>
                                    <th scope="row">{{$loop->iteration + (($campaigns->currentPage()-1) * $campaigns->perPage())}}</th>
                                    <td><a href="{{route('category.show',$campaign->id)}}"> {{$campaign->name}}</a></td>
                                    <td>{{jdate($campaign->start)->format('y/m/d - H:m:s')}}</td>
                                    <td>{{jdate($campaign->end)->format('y/m/d - H:m:s')}}</td>
                                    <td>{{jdate($campaign->created_at)->format('y/m/d')}}</td>
                                    <td>{{jdate($campaign->updated_at)->format('y/m/d')}}</td>
                                    <td class="text-right">
                                        <div class="col-md-12">
                                            <form action="{{route('campaign.destroy',$campaign->id)}}" method="post">
                                                @method('delete')
                                                @csrf
                                                <a href="{{route('campaign.edit',$campaign->id)}}" class="btn btn-sm  btn-outline-secondary btn-square">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <button type="submit" class="btn btn-sm btn-outline-secondary btn-square">
                                                    <i class="fas fa-trash"></i>
                                                </button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @else
                        <div class="alert alert-secondary text-center" role="alert">
                            رکوردی برای نمایش وجود ندارد.
                        </div>
                    @endif
                </div>

                @if($campaigns->total() > $campaigns->perPage())
                    <div class="card-footer">{{$campaigns->links()}}</div>
                @endif
            </div>
        </div>
    </div>
@endsection
@section('scripts')

    <script>

        function activate(id){
            $.ajax({url: '/api/v1/category/activate/'+id , success: function(result){
                    toastr.info('وضعیت دسته‌بندی تغییر کرد!');

                }});
        }
    </script>
@endsection