routes/web.php
<?php
Route::middleware('auth')->group( function () {
    Route::get('/', 'DashboardController@index');
    Route::get('/sellsDashboard', 'DashController@sell')->name('sellsDashboard');

    Route::resources([
        'category'     =>  'CategoriesController',
        'product'      =>  'ProductsController',
        'city'         =>  'CitiesController',
        'supplier'     =>  'VendorsController',
        'visitor'      =>  'VisitorsController',
        'log'          =>  'LogsController',
        'campaign'     =>  'CampaignsController',
        'user'         =>  'usersController',
        'permission'   =>  'PermissionsController',
        'driver'       =>  'DriversController',
        'notification' =>  'NotificationsController',
        'blog'         =>  'PostsController'
    ]);


    Route::post('driver/clear', 'DriversController@clear')->name('driver.clear');
});
Auth::routes();


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded = [];
    public function parent()
    {
        return $this->belongsTo(Category::class, 'parent_id')->with('parent');
    }
    public function children(){
        return $this->hasMany(Category::class);
    }

    public function activate(){
        $this->status = !$this->status;
        $this->update();
    }
}

app/Http/Controllers/Api/v1/CategoriesController.php
<?php

namespace App\Http\Controllers\api\v1;

use App\Category;
use App\Http\Controllers\Controller;
use App\Http\Resources\Api\v1\CategoryCollection;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    public function index(){
        $category = Category::all();
        return response()->json($category);
    }

    public function activate(Category $category)
    {
        $category->activate();
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{

    public function index()
    {
        $categories = Category::with('parent')->orderBy('created_at','desc')->paginate(15);
        return view('pages.category.list',compact('categories'));
    }

    public function create()
    {
        $categories = Category::all();
        return view('pages.category.create',compact('categories'));
    }

    public function store()
    {
        if(request('submit')){
            $category = Category::create($this->validateData());
            $this->storeImage($category);

            return redirect(route('category.index'))->with('success','دسته‌بندی مورد نظر ایجاد شد');
        }
        if(request('submitNew')){
            $category = Category::create($this->validateData());
            $this->storeImage($category);
            return redirect(route('category.create'))->with('success','دسته‌بندی مورد نظر ایجاد شد');
        }

    }

    public function show(Category $category)
    {
        return view('pages.category.show',compact('category'));
    }

    public function edit(Category $category)
    {
        $categories = Category::all();
        return view('pages.category.edit',compact(['category','categories']));
    }
    public function update(Category $category)
    {
        $category->update($this->validateData());
        $this->storeImage($category);
        return redirect(route('category.index'))->with('success','دسته‌بندی مورد نظر ویرایش شد');;
    }

    public function destroy(Category $category)
    {

        $category->delete();
        return redirect(route('category.index'));
    }

    private function validateData()
    {
        return request()->validate([
            'name'=> 'required',
            'parent_id'=>'sometimes',
            'status'=> 'sometimes',
            'photo'=>'sometimes|file|image|max:1000'
        ]);
    }

    private function storeImage($category)
    {
        if (request()->has('photo')) {
            $category->update([
                'photo' => request()->photo->store('uploads', 'public'),
            ]);
        }
    }

    public function search()
    {
        $categories = Category::where('parent_id', 0)->get();
        return view('pages.category.search',compact('categories'));
    }
}

resources/views/pages/category/create.blade.php
@extends('master')

@section('breadcrumb')
    <h3 class="page-title">دسته‌بندی جدید</h3>
    <!-- begin::breadcrumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">داشبورد</a></li>
            <li class="breadcrumb-item"><a href="{{route('category.index')}}">لیست دسته‌بندی‌ها</a></li>
            <li class="breadcrumb-item active" aria-current="page">دسته‌بندی جدید</li>
        </ol>
    </nav>
    <!-- end::breadcrumb -->
@endsection
@section('content')
    <div class="row">
        <div class="col-md-9">
            <div class="card">
                <div class="card-body">
                    <form action="{{route('category.store')}}" method="post" enctype="multipart/form-data" class="needs-validation" novalidate="">
                        @csrf
                        <div class="form-group">
                            <label for="">نام دسته‌بندی</label>
                            <input type="text" name="name" id="" class="form-control" placeholder="" aria-describedby="helpId" required="">
                            <div class="valid-feedback">
                                صحیح است!
                            </div>
                            <div class="invalid-feedback">
                                لطفا نام دسته‌بندی را وارد کنید.
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="">عکس</label>
                            <div class="custom-file">
                                <input type="file" name="photo" class="custom-file-input" id="customFile">
                                <label class="custom-file-label" for="customFile">انتخاب فایل</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="">وضعیت دسته‌بندی</label>
                            <div class="custom-control custom-checkbox custom-checkbox-success">
                                <input type="hidden" name="status"  value="0">
                                <input type="checkbox" class="custom-control-input" name="status" id="customCheck2" value="1">
                                <label class="custom-control-label" for="customCheck2">فعال</label>
                            </div>
                        </div>

                        <div class="form-group">
                            <input type="submit" name="submit" class="btn btn-success" value="ذخیره"/>
                            <input type="submit" name="submitNew" class="btn btn-secondary" value="ذخیره و جدید"/>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card bg-transparent">
                <div class="card-header">
                    <h5>راهنما</h5>
                </div>
                <div class="card-body">
                    <p><small>
                            در این صفحه می‌توانید دسته‌بندی‌های جدید بسازید.
                        </small></p>
                    <p class="m-b-0">نام دسته‌بندی</p>
                    <p><small>توجه داشته باشید که نام دسته‌بندی را حتما وارد کنید.</small></p>
                    <p class="m-b-0">دسته‌بندی والد</p>
                    <p class="text-justify"><small class="text-justify">در صورتی که می‌خواهید دسته‌بندی مورد نظرتان زیرگروه دسته‌بندی دیگری قرار گیرد، نام دسته‌بندی مورد نظر را از این لیست انتخاب کنید. در غیر این صورت این گزینه را روی <strong>«والد»</strong> تنظیم کنید.</small></p>
                    <p class="m-b-0">عکس دسته‌بندی</p>
                    <p class="text-justify"><small class="text-justify">هر دسته‌بندی می‌تواند یک عکس داشته باشد. این عکس به عنوان یک آیکون در اپلیکیشن نمایش داده می‌شود. توجه داشته باشید که آپلود عکس اجباری نیست اما دسته‌بندی‌هایی که عکس نداشته باشند در صفحه اصلی اپلیکیشن نمایش داده نمی‌شوند.</small></p>
                    <p class="m-b-0">وضعیت دسته‌بندی</p>
                    <p class="text-justify"><small class="text-justify">به صورت پیش‌فرض دسته‌بندی، دسته‌بندی‌هایی که فعال نباشند در هیچ لیستی نمایش داده نمی‌شود.</small></p>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        //  Form Validation
        window.addEventListener('load', function () {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function (form) {
                form.addEventListener('submit', function (event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    </script>
@endsection

resources/views/pages/category/edit.blade.php
@extends('master')

@section('breadcrumb')
    <h3 class="page-title">{{$category->name}}</h3>
    <!-- begin::breadcrumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">داشبورد</a></li>
            <li class="breadcrumb-item"><a href="{{route('category.index')}}">لیست دسته‌بندی‌ها</a></li>
            <li class="breadcrumb-item"><a href="{{route('category.index')}}">ویرایش سته‌بندی‌ها</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{$category->name}}</li>
        </ol>
    </nav>
    <!-- end::breadcrumb -->
@endsection
@section('content')
    <div class="row">
        <div class="col-md-9">
            <div class="card">
                <div class="card-body">
                    <form action="{{route('category.store')}}" method="post" enctype="multipart/form-data" class="needs-validation" novalidate="">
                        @csrf
                        <div class="form-group">
                            <label for="">نام دسته‌بندی</label>
                            <input type="text" name="name" id="" class="form-control" placeholder="" aria-describedby="helpId" required="" value="{{$category->name}}">
                            <div class="valid-feedback">
                                صحیح است!
                            </div>
                            <div class="invalid-feedback">
                                لطفا نام دسته‌بندی را وارد کنید.
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="">عکس</label>
                            <div class="custom-file">
                                <input type="file" name="photo" class="custom-file-input" id="customFile">
                                <label class="custom-file-label" for="customFile">انتخاب فایل</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="">وضعیت دسته‌بندی</label>
                            <div class="custom-control custom-checkbox custom-checkbox-success">
                                <input type="hidden" name="status" value="0">
                                <input type="checkbox" class="custom-control-input" name="status" id="customCheck2" value="1" {{$category->status == 1 ? 'checked':null}}>
                                <label class="custom-control-label" for="customCheck2">فعال</label>
                            </div>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-success">ذخیره</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        @if($category->photo)
            <div class="col-md-3">
                <div class="card">
                    <div class="card-body">
                        <img class="img-thumbnail img-fluid" src="{{asset('storage/'.$category->photo)}}" alt="">
                    </div>
                </div>
            </div>
        @endif
    </div>
@endsection
@section('scripts')
    <script>
        //  Form Validation
        window.addEventListener('load', function () {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function (form) {
                form.addEventListener('submit', function (event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                    }
                    form.classList.add('was-validated');
                }, false);
            });
        }, false);
    </script>
@endsection

resources/views/pages/category/list.blade.php
@extends('master')

@section('breadcrumb')
    <h3 class="page-title">لیست دسته‌بندی‌ها</h3>
    <!-- begin::breadcrumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">داشبورد</a></li>
            <li class="breadcrumb-item active" aria-current="page">لیست دسته‌بندی‌ها</li>
        </ol>
    </nav>
    <!-- end::breadcrumb -->
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                @if($categories->total() > $categories->perPage())
                    <div class="card-footer">{{$categories->links()}}</div>
                @endif
                <div class="card-body">
                    @if(count($categories))
                        <table class="table" id="dataTable">
                            <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">نام دسته‌بندی</th>
                                <th scope="col">عکس</th>
                                <th scope="col">وضعیت</th>
                                <th scope="col">تاریخ ایجاد</th>
                                <th scope="col">تاریخ ویرایش</th>
                                <th class="text-right" scope="col"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($categories as $category)
                                <tr>
                                    <th scope="row">{{$loop->iteration + (($categories->currentPage()-1) * $categories->perPage())}}</th>
                                    <td>{{$category->name}}</a></td>
                                    <td>@if($category->photo)  <i class="fal fa-check text-success"></i>@else<i class="fal fa-times text-danger"></i>@endif</td>
                                    <td>
                                        <div class="form-group">
                                            <div class="custom-control custom-switch custom-checkbox-success">
                                                <input type="checkbox" class="custom-control-input" id="customSwitch-{{$category->id}}" {{$category->status?'checked':null}} onChange="activate({{$category->id}})">
                                                <label class="custom-control-label" for="customSwitch-{{$category->id}}"></label>
                                            </div>
                                        </div>
                                    </td>
                                    <td>{{jdate($category->created_at)->format('y/m/d')}}</td>
                                    <td>{{jdate($category->updated_at)->format('y/m/d')}}</td>
                                    <td class="text-right">
                                        <div class="col-md-12">
                                            <form action="{{route('category.destroy',$category->id)}}" method="post">
                                                @method('delete')
                                                @csrf
                                                <div class="btn-group btn-group-sm">
                                                    <a href="{{route('category.edit',$category->id)}}" class="btn btn-sm btn-outline-light">
                                                        <i class="fas fa-edit"></i>
                                                    </a>
                                                    <button type="submit" class="btn btn-sm btn-outline-light">
                                                        <i class="fas fa-trash"></i>
                                                    </button>
                                                </div>

                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @else
                        <div class="alert alert-secondary text-center" role="alert">
                            رکوردی برای نمایش وجود ندارد.
                        </div>
                    @endif
                </div>

                @if($categories->total() > $categories->perPage())
                    <div class="card-footer">{{$categories->links()}}</div>
                @endif
            </div>
        </div>
    </div>
@endsection
@section('scripts')

    <script>

        function activate(id){
            $.ajax({url: '/api/v1/category/activate/'+id , success: function(result){
                    toastr.info('وضعیت دسته‌بندی تغییر کرد!');

                }});
        }
    </script>
@endsection

resources/views/pages/category/search.blade.php
@extends('master')

@section('breadcrumb')
    <h3 class="page-title">جستحوی دسته‌بندی‌ها دسته‌بندی‌ها</h3>
    <!-- begin::breadcrumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">داشبورد</a></li>
            <li class="breadcrumb-item active" aria-current="page">جستجوی دسته‌بندی‌ها</li>
        </ol>
    </nav>
    <!-- end::breadcrumb -->
@endsection
@section('content')
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <form action="">
                        <div class="form-group">
                            <label for="">جستجو</label>
                            <input type="text" name=" " id="" class="form-control" placeholder="" aria-describedby="helpId">
                        </div>
                        <div class="form-group">
                            <label for="">وضعیت: </label>
                            <div class="custom-control custom-radio custom-control-inline">
                                <input type="radio" id="customCheckBoxInline1" name="status" class="custom-control-input" value="1">
                                <label class="custom-control-label" for="customCheckBoxInline1">فعال</label>
                            </div>
                            <div class="custom-control custom-radio custom-control-inline">
                                <input type="radio" id="customCheckBoxInline2" name="status" class="custom-control-input" value="0">
                                <label class="custom-control-label" for="customCheckBoxInline2">غیر فعال</label>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="">دسته‌بندی والد</label>
                            <select class="form-control" name="" id="">
                                @forelse($categories as $category)
                                    <option value="{{$category->id}}">{{$category->name}}</option>
                                @empty
                                    <option>دسته‌بندی وجود ندارد</option>

                                @endforelse
                            </select>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">جستجو</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <div class="alert alert-secondary text-center" role="alert">
                        نتیجه‌ای برای نمایش وجود ندارد.
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/category/show.blade.php
@extends('master')

@section('breadcrumb')
    <h3 class="page-title">{{$category->name}}</h3>
    <!-- begin::breadcrumb -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">داشبورد</a></li>
            <li class="breadcrumb-item"><a href="{{route('category.index')}}">داشبورد</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{$category->name}}</li>
        </ol>
    </nav>
    <!-- end::breadcrumb -->
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-8">
                            <h3><strong>نام دسته‌بندی:</strong> {{$category->name}}</h3>
                            <h4><strong>دسته‌بندی والد:</strong> {{$category->parent?$category->parent->name:'دسته والد'}}</h4>
                            <h4><strong>وضعیت دسته‌بندی:</strong> {{$category->status===1? 'فعال':'غیر‌فعال'}}</h4>
                        </div>‍
                        @if($category->photo != null)
                            <div class="col-md-4">
                                <img class="img-fluid img-thumbnail" src="{{asset('storage/'.$category->photo)}}" alt="">

                            </div>
                        @endif
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection